server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: dialog-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-db:5432/dialog_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://eureka-server:8761/eureka/}

authentication:
  service:
    validation:
      url: ${AUTH_VALIDATE_URL:http://mc-authentication:8081/api/v1/auth/validate}