server:
  port: ${SERVER_PORT:8003}

spring:
  application:
    name: ms-gateway

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://eureka-server:8761/eureka/}
