server:
  port: ${SERVER_PORT:8085}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-db:5432/post_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}

security:
  authenticate:
    url: ${SECURITY_AUTH_URL:http://mc-authentication:8081}
    path: ${SECURITY_AUTH_PATH:/api/v1/auth/validate}